version: '3.8'

services:
  # RitZone Backend API (Node.js + Express + Supabase)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ritzone-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      NODE_ENV: production
      BACKEND_PORT: 8001
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      POSTGRES_CONNECTION_STRING: ${POSTGRES_CONNECTION_STRING}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    env_file:
      - .env
    networks:
      - ritzone-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  ritzone-network:
    driver: bridge
